
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b"`J)^'\xa2\x03\xf2~y\xd3jiA\x92\x1e"
    
_lr_action_items = {'$end':([2,3,5,23,],[-3,0,-2,-4,]),'=':([8,],[20,]),'$':([6,29,],[9,9,]),'NAME':([0,2,3,5,6,7,9,23,26,29,],[1,-3,1,-2,8,17,8,-4,8,8,]),':':([1,17,],[4,26,]),'[':([4,],[6,]),'(':([6,9,29,],[7,7,7,]),')':([8,18,19,27,31,],[-1,-20,-15,-19,33,]),'VALUE':([20,],[27,]),',':([8,10,12,13,14,15,18,19,21,22,24,25,27,32,33,],[-1,-14,-12,-13,-11,-1,-20,-15,-18,-17,29,-8,-19,-7,-16,]),']':([6,8,10,11,12,13,14,15,16,18,19,21,22,24,25,27,28,29,30,32,33,],[-1,-1,-14,23,-12,-13,-11,-1,-6,-20,-15,-18,-17,-1,-8,-19,-5,-9,-10,-7,-16,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'result':([0,3,],[2,5,]),'list_attr_simple':([6,29,],[10,10,]),'node_attrs_opt':([6,],[11,]),'attr_child':([6,9,29,],[12,22,12,]),'more_attrs_maybe':([15,],[24,]),'list_attr_child':([6,29,],[13,13,]),'attr_simple':([6,9,26,29,],[14,21,31,14,]),'equal_to_val_opt':([8,],[19,]),'attr':([6,29,],[15,32,]),'comma_opt':([24,],[28,]),'empty':([6,8,15,24,],[16,18,25,30,]),'results':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> results","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',65),
  ('results -> results result','results',2,'p_goal','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',68),
  ('results -> result','results',1,'p_goal2','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',72),
  ('result -> NAME : [ node_attrs_opt ]','result',5,'p_result','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',76),
  ('node_attrs_opt -> attr more_attrs_maybe comma_opt','node_attrs_opt',3,'p_node_attrs_opt1','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',80),
  ('node_attrs_opt -> empty','node_attrs_opt',1,'p_node_attrs_opt2','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',84),
  ('more_attrs_maybe -> more_attrs_maybe , attr','more_attrs_maybe',3,'p_more_attrs_opt1','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',88),
  ('more_attrs_maybe -> empty','more_attrs_maybe',1,'p_more_attrs_opt2','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',92),
  ('comma_opt -> ,','comma_opt',1,'p_comma_opt','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',96),
  ('comma_opt -> empty','comma_opt',1,'p_comma_opt','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',97),
  ('attr -> attr_simple','attr',1,'p_attr','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',101),
  ('attr -> attr_child','attr',1,'p_attr','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',102),
  ('attr -> list_attr_child','attr',1,'p_attr','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',103),
  ('attr -> list_attr_simple','attr',1,'p_attr','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',104),
  ('attr_simple -> NAME equal_to_val_opt','attr_simple',2,'p_attr1','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',109),
  ('attr_child -> ( NAME : attr_simple )','attr_child',5,'p_attr2','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',113),
  ('list_attr_child -> $ attr_child','list_attr_child',2,'p_attr3','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',117),
  ('list_attr_simple -> $ attr_simple','list_attr_simple',2,'p_attr4','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',121),
  ('equal_to_val_opt -> = VALUE','equal_to_val_opt',2,'p_equal_to_val_opt1','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',125),
  ('equal_to_val_opt -> empty','equal_to_val_opt',1,'p_equal_to_val_opt2','c:\\users\\karuna\\desktop\\jython\\python\\my modules\\py2c\\py2c\\dual_ast.py',129),
]
